### ISSUE TITLE
Property 'CCD_FRAME' of device 'indi_pylibcamera' is read only

### ISSUE THREAD

**Issue by sajmons** [art-den/astra_lite#1]
Anothewr issue with AstraLite software and indi_pylibcamera driver. After I press "Take shot" buton I get this error: Property 'CCD_FRAME' of device 'indi_pylibcamera' is read only.
![image](https://user-images.githubusercontent.com/7437280/236636300-63c8c975-5f25-456d-bf34-27f3badd1f03.png)

**Comment by sajmons** [comment]
Here is log. I think that this error came with version 0.0.35 or later. Version of indi_pylibcamera is 1.8.0.
[astra_lite_2023-05-06_21-03-32.log](https://github.com/art-den/astra_lite/files/11413163/astra_lite_2023-05-06_21-03-32.log)

**Comment by art-den** [comment]
This property is really read-only. I will disable crop selection and will not set frame property if it is not writable

**Comment by sajmons** [comment]
I can confirm, that action "Take shot" is working again in version 0.0.58.
