### ISSUE TITLE
Image capture not working with Raspbery PI LibCamera C++ INDI driver

### ISSUE THREAD

**Issue by sajmons** [art-den/astra_lite#11]
Today I tried astra_lite with LibCamera INDI driver (not indi_pylibcamera) and had no success.
I dont know where problem is, I have attached some screen shots, INDI properties and very verbose log.

I have tested on fresh instalation of Stellarmate 1.8.1.

`cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
`

Conection to INDI server succeded:
![image](https://github.com/art-den/astra_lite/assets/7437280/ae702c8c-3382-4112-aa0d-8f645c85303f)

First time shot is all black, second one never finishes:
![image](https://github.com/art-den/astra_lite/assets/7437280/0ae90bbf-07b8-48a2-8b03-ad66d5c8a68e)

[INDI_properties.txt](https://github.com/art-den/astra_lite/files/14597816/INDI_properties.txt)

[astra_lite_2024-03-14_07-22-41.log](https://github.com/art-den/astra_lite/files/14597820/astra_lite_2024-03-14_07-22-41.log)

**Comment by art-den** [comment]
@sajmons 
Thanks for report! It looks like strange bug in AstraLite. But version 0.0.90 is very old. First try latest (0.0.124) version and inform me if the bug is reproduced in it

**Comment by sajmons** [comment]
I'm closing this, becasue capturing its working in version 0.0.130.
