### ISSUE TITLE
Help / Open logs folder not working on Windows

### ISSUE THREAD

**Issue by sajmons** [art-den/astra_lite#2]
When I select "Help/Open logs folder" from menu, nothing happens.

**Comment by art-den** [comment]
Hi, @sajmons 
Does path to log folder contains non-latin letters?

**Comment by sajmons** [comment]
No, here is the path: C:\Users\Simon\AppData\Roaming\.astra_lite\logs

**Comment by art-den** [comment]
Fixed in v0.0.82
