### ISSUE TITLE
Shot settings not refreshing after changing camera

### ISSUE THREAD

**Issue by sajmons** [art-den/astra_lite#4]
I started indi server with indi_pylibcamera and indi_simulator_ccd.
When I change Camera on "Camera & focuser" tab, "Shot settings" should refresh acording too selected camera.

Before camera change:
![image](https://github.com/art-den/astra_lite/assets/7437280/3c7f5539-418b-40a1-be79-1174c8841646)

After camera change:
![image](https://github.com/art-den/astra_lite/assets/7437280/3391888a-e852-421b-9b1f-419bacc13050)

Expected after camera changed:
![image](https://github.com/art-den/astra_lite/assets/7437280/e8905532-2ecf-4a27-be42-fed9aba291d2)

**Comment by art-den** [comment]
I plan to support several cameras little later. Let the issue remain so as not to forget about it

**Comment by art-den** [comment]
Done
