### ISSUE TITLE
Take shot results in: Aborted (core dumped)

### ISSUE THREAD

**Issue by petmos** [art-den/astra_lite#6]
I run AstraLite on my ubuntu 22.04 (x86_64) and connect to my remote INDI server.
After connection is established I try to take a shot but AstraLite immediately crashes with: Aborted (core dumped)

**Comment by petmos** [comment]
[astra_lite_2023-05-29_16-52-59.log](https://github.com/art-den/astra_lite/files/11592666/astra_lite_2023-05-29_16-52-59.log)

**Comment by art-den** [comment]
@petmos 
Thanks for log! I will investigate. There is something wrong in frame noise level calculation

**Comment by art-den** [comment]
@petmos 
I think I fixed this bug. Do you build AstraLite from sources manually or install from deb?

**Comment by petmos** [comment]
@art-den I build it from sources. But I have no experiences with rust/cargo.
How can I rebuild it?
_git pull && cargo build --release_
or something else?

**Comment by art-den** [comment]
@petmos yes,
```
git pull
cargo build --release
```
is enough to build the latest sources

**Comment by petmos** [comment]
Looks good now.
Great job. Thank you very much.
