### ISSUE TITLE
Feature: Allow hostnames and port number

### ISSUE THREAD

**Issue by petmos** [art-den/astra_lite#7]
The field "Connect remote:" allows olny IP addresses.
When using hostnames or port numbers like 127.0.0.1:8624 connecting fails with: 
"Error: Invalid socket address syntax"

Because ip Addresses can change when using DHCP it would be fine to use hostnames.
Port number will be most of the time the default one.
But perhaps someone must change it.
In this case a field for the port number would be helpful.

**Comment by art-den** [comment]
I know about it. I will try to do this before release

**Comment by art-den** [comment]
Done in 0.0.93
