### ISSUE TITLE
Freeze when Simple Guiding is enabled

### ISSUE THREAD

**Issue by petmos** [art-den/astra_lite#8]
I'm using a Skywatcher Az-GTi and want to use "Simple Guiding".
With latest version "0.0.98" AstraLite freezes when "Simple Guiding" is enabled.
[Freezing_Simple_Guide_astra_lite_2023-08-19_16-54-07.log](https://github.com/art-den/astra_lite/files/12386167/Freezing_Simple_Guide_astra_lite_2023-08-19_16-54-07.log)

When I try to run "Test calibration" it complains about not finding "Guide_Rate". 
![grafik](https://github.com/art-den/astra_lite/assets/1385807/f84a57dc-1c1c-414d-a48e-b2ed14262d8b)

With older versions "Simple Guiding" does not work (no motion, no new light frames), too. But AstraLite doesn't freeze.

**Comment by art-den** [comment]
Hi, 
First, I haven't tested AstraLite with an alt-azimuth mount. 
Second, it looks like your mount's driver supports only 1x guide rate. That's why "guide rate" property is not exported by driver. I will try to fix it in AstraLite. Thanks for logs!

**Comment by art-den** [comment]
@petmos I did some fixes. You can try and let me know the results

**Comment by petmos** [comment]
Looks good now.
No freezes anymore.
