### ISSUE TITLE
Test Calibration failes with "Device `` not found"

### ISSUE THREAD

**Issue by petmos** [art-den/astra_lite#9]
When I hit "Test Calibration" before starting "Live Stacking" it fails with 
![grafik](https://github.com/art-den/astra_lite/assets/1385807/48df79ad-d593-4fac-8d6f-21bbabf793a3)

[Test_Calibtration_No_Device_astra_lite_2023-08-27_19-57-53.log](https://github.com/art-den/astra_lite/files/12448804/Test_Calibtration_No_Device_astra_lite_2023-08-27_19-57-53.log)

When I start first  "Live Stacking"  then "Test Calibration" seems to work.

**Comment by art-den** [comment]
Fixed. But I will push fix to the repo little later

**Comment by art-den** [comment]
Fixed some time ago. Forgot to close
